import type { Metadata } from 'next';
import { Rajdhani } from 'next/font/google';
import { NavBar } from '@/shared/layout/NavBar';
import '@/shared/styles/main.scss';

const rajdhani = Rajdhani({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  fallback: ['sans-serif'],
});

export const metadata: Metadata = {
  title: 'FerLux Auto',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" data-theme="dark">
      <body className={`${rajdhani.className}`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
